version: "3.8"
services:
    db:
        image: postgres:14.2-alpine
        restart: always
        environment:
            POSTGRES_DB: springbootdb
            POSTGRES_PASSWORD: 12345
        ports:
            - "5432:5432"
        volumes:
            - C:/Projeto/sdb:/var/lib/postgressq/data
